### ISSUE TITLE
Bug: Validators for DecimalField

### ISSUE THREAD

**Issue by dariodinizg** [cesarbruschetta/api-fintech#17]
**Describe the bug**
Validators inside DecimalField for our Loan and Payment models is causing bugs, cause they try to call "return a.lower is None or a.lower < b", but acuse "AttributeError" due to decimal.Decimal' object has no attribute 'lower' .

**To Reproduce**
Go to admin page and try to post a new Loan.

**Expected behavior**
Get an error page:
AttributeError at /admin/calculator/payment/add/
'decimal.Decimal' object has no attribute 'lower'

The two last lines point the exception.

**Comment by dariodinizg** [comment]
I think the only validation we can add is to check if the value is positive. I'm writing a custom validation as declared here:
https://docs.djangoproject.com/en/1.10/ref/validators/

**Comment by dariodinizg** [comment]
And thinking about it, validators should be left to the integrated part for forms, no?

**Comment by Leonardoperrella** [comment]
How Can I Get this issue?

**Comment by Leonardoperrella** [comment]
I´t Woks with this.
from django.forms import DecimalField
from django.core.validators import MaxValueValidator, MinValueValidator

    client = models.ForeignKey(Client, on_delete=models.DO_NOTHING)
    amount = models.DecimalField('Amount', max_digits=15,
                                 decimal_places=2,
                                 validators=[MinValueValidator(0.01)
                                 ])
    term = models.IntegerField('Term',
                                validators=[MinValueValidator(1)
                                ])
    rate = models.DecimalField('Rate', max_digits=15,
                                 decimal_places=2,
                                  validators=[MinValueValidator(1)
                                  ])
    date_initial = models.DateTimeField('Date creation', auto_now=False, auto_now_add=False)

**Comment by julianeventeu** [comment]
> How Can I Get this issue?

You should click on the button "assign yourself"

![image](https://user-images.githubusercontent.com/11297954/57540141-64e01480-7322-11e9-875b-38059071fb6a.png)

**Comment by julianeventeu** [comment]
> I´t Woks with this.
> from django.forms import DecimalField
> from django.core.validators import MaxValueValidator, MinValueValidator
> 
> ```
> client = models.ForeignKey(Client, on_delete=models.DO_NOTHING)
> amount = models.DecimalField('Amount', max_digits=15,
>                              decimal_places=2,
>                              validators=[MinValueValidator(0.01)
>                              ])
> term = models.IntegerField('Term',
>                             validators=[MinValueValidator(1)
>                             ])
> rate = models.DecimalField('Rate', max_digits=15,
>                              decimal_places=2,
>                               validators=[MinValueValidator(1)
>                               ])
> date_initial = models.DateTimeField('Date creation', auto_now=False, auto_now_add=False)
> ```

Create a branch, change the code, run the tests and request a PR to branch development, please.

**Comment by Leonardoperrella** [comment]
I't doesn't appear to me. I'm trying to append the print screen.

****
![image](https://user-images.githubusercontent.com/8564958/57541001-70343f80-7324-11e9-90a6-161f32f49d46.png)
